# Generated by Django 2.1.2 on 2019-02-13 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, unique_for_year='pub_date', verbose_name='Название')),
                ('pub_date', models.DateField(verbose_name='Дата публикации')),
                ('genre', models.CharField(max_length=60, verbose_name='Жанр')),
                ('isbn', models.CharField(max_length=250, unique=True, verbose_name='ISBN код')),
                ('author', models.ManyToManyField(to='authors.Author')),
            ],
        ),
    ]
