# Generated by Django 2.1.2 on 2019-02-13 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_auto_20190213_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='authors',
            field=models.ManyToManyField(related_name='author', to='authors.Author'),
        ),
    ]
